### ISSUE TITLE
support single 868MHz TX antenna

### ISSUE THREAD

**Issue by alexanderdross** [TheMiNuS/Stratux-daughter-board#3]
related to #3 of [https://github.com/b3nn0/stratux/discussions/154#discussioncomment-1988424](https://github.com/b3nn0/stratux/discussions/154#discussioncomment-1988424)
integrate an "RF Power Divider" or "RF Power Combiner" or enable synchronization of the two RF chips so both can send your aircraft's position through multiple protocols (OGNTP + legacy) via one antenna

**Comment by TheMiNuS** [comment]
Today there is two RF Chips that can be used individually. The software used to operate this board can operate with only 1 chip with all protools needed. This issue is more related to code than hardware.

Will close this one. Maybe a new board with only one chip can be done in addition to this one with two chips and let people choose depending on their usage.
